"""AI providers for deterministic and LLM-assisted test-case generation."""

from __future__ import annotations

import json
import os
from abc import ABC, abstractmethod
from typing import Any

from .models import TestCase, TestCaseSpec, TestStep
from .utils import slugify


class AbstractAIProvider(ABC):
    """Base interface for all generation providers."""

    @abstractmethod
    def generate(self, spec: TestCaseSpec) -> list[TestCase]:
        """Generate test cases from a structured specification."""
        raise NotImplementedError


class LocalMockAIProvider(AbstractAIProvider):
    """Deterministic provider for local development, demos and CI."""

    def generate(self, spec: TestCaseSpec) -> list[TestCase]:
        """Generate predictable cases from normal inputs and edge cases."""
        cases: list[TestCase] = []
        tags = list(spec.metadata.get("tags", []) or [])

        for index, item in enumerate(spec.inputs, start=1):
            cases.append(
                self._build_case(
                    index=index,
                    spec=spec,
                    item=item,
                    kind="happy_path",
                    default_expected={"status": "success"},
                    tags=tags,
                )
            )

        offset = len(cases)
        for edge_index, item in enumerate(spec.edge_cases, start=1):
            cases.append(
                self._build_case(
                    index=offset + edge_index,
                    spec=spec,
                    item=item,
                    kind="edge_case",
                    default_expected={"status": "error"},
                    tags=[*tags, "edge-case"],
                )
            )

        return cases

    @staticmethod
    def _build_case(
        *,
        index: int,
        spec: TestCaseSpec,
        item: dict[str, Any],
        kind: str,
        default_expected: dict[str, Any],
        tags: list[str],
    ) -> TestCase:
        case_name = slugify(str(item.get("name", f"case_{index}")))
        spec_name = slugify(spec.title)
        payload = item.get("payload", item.get("input", {}))
        expected = item.get("expected", default_expected)

        return TestCase(
            id=f"TC-{index:03d}",
            name=f"{spec_name}_{case_name}",
            description=item.get("description", f"Validate {kind.replace('_', ' ')} scenario: {case_name}"),
            steps=[
                TestStep(
                    action=f"Exercise {spec.target} '{spec.subject}'",
                    input=payload,
                    expected=expected,
                )
            ],
            tags=tags,
        )


class OpenAIProvider(AbstractAIProvider):
    """OpenAI provider using the modern OpenAI Python SDK client."""

    def __init__(self, api_key: str | None = None, model: str | None = None) -> None:
        from openai import OpenAI

        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        if not self.api_key:
            raise RuntimeError("OPENAI_API_KEY is required when provider='openai'")

        self.model = model or os.getenv("OPENAI_MODEL", "gpt-4o-mini")
        self.client = OpenAI(api_key=self.api_key)

    def generate(self, spec: TestCaseSpec) -> list[TestCase]:
        """Ask OpenAI to produce strict JSON and map it into TestCase objects."""
        system_prompt = (
            "You are a senior QA automation engineer. Return only valid JSON with a top-level "
            "'testcases' array. Each testcase must include id, name, description, tags and steps. "
            "Each step must include action, input and expected."
        )
        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(spec.to_dict(), ensure_ascii=False)},
            ],
            response_format={"type": "json_object"},
            temperature=0.2,
        )
        text = response.choices[0].message.content or "{}"
        payload = json.loads(text)
        raw_cases = payload.get("testcases", payload if isinstance(payload, list) else [])

        cases: list[TestCase] = []
        for index, item in enumerate(raw_cases, start=1):
            steps = [TestStep(**step) for step in item.get("steps", [])]
            cases.append(
                TestCase(
                    id=str(item.get("id", f"TC-{index:03d}")),
                    name=slugify(str(item.get("name", f"case_{index}"))),
                    description=str(item.get("description", "Generated by OpenAI")),
                    steps=steps,
                    tags=list(item.get("tags", [])),
                )
            )
        return cases
