"""Render generated test cases into professional output formats."""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, Template

from .models import TestCase, TestCaseSpec
from .utils import dump_json, ensure_parent_dir, safe_repr, slugify

PYTEST_TEMPLATE = '''"""Auto-generated pytest scenarios for {{ spec.title }}.

Generated by ai-testcase-generator. Review TODO sections and wire them to the
real system under test before treating these tests as production assertions.
"""

import pytest


TEST_CASES = {{ cases_literal }}


@pytest.mark.parametrize("case", TEST_CASES, ids=[case["name"] for case in TEST_CASES])
def test_{{ spec_slug }}(case):
    """{{ spec.description or 'Generated scenario' }}"""
    for step in case["steps"]:
        # Step: {{ "{" }}step['action']{{ "}" }}
        # Input: {{ "{" }}step['input']{{ "}" }}
        # Expected: {{ "{" }}step['expected']{{ "}" }}
        # TODO: call your {{ spec.target }} under test and assert against step["expected"].
        assert step["expected"] is not None
'''

MARKDOWN_TEMPLATE = """# {{ spec.title }} - Generated Test Cases

{{ spec.description }}

**Target:** `{{ spec.target }}`  
**Subject:** `{{ spec.subject }}`

{% for case in testcases %}
## {{ case.id }} - {{ case.name }}

{{ case.description }}

**Tags:** {{ case.tags | join(', ') if case.tags else 'none' }}

{% for step in case.steps %}
### Step {{ loop.index }}

- **Action:** {{ step.action }}
- **Input:** `{{ step.input | safe_repr }}`
- **Expected:** `{{ step.expected | safe_repr }}`
{% endfor %}
{% endfor %}
"""


def _environment() -> Environment:
    env = Environment(autoescape=False, trim_blocks=True, lstrip_blocks=True)
    env.filters["safe_repr"] = safe_repr
    return env


def render_pytest_file(path: str | Path, testcases: list[TestCase], spec: TestCaseSpec) -> None:
    """Render a parametrized pytest module."""
    ensure_parent_dir(path)
    template: Template = _environment().from_string(PYTEST_TEMPLATE)
    content = template.render(
        spec=spec,
        spec_slug=slugify(spec.title),
        cases_literal=safe_repr([case.to_dict() for case in testcases], max_length=100_000),
    )
    Path(path).write_text(content, encoding="utf-8")


def render_markdown_file(path: str | Path, testcases: list[TestCase], spec: TestCaseSpec) -> None:
    """Render generated cases as reviewer-friendly Markdown documentation."""
    ensure_parent_dir(path)
    template: Template = _environment().from_string(MARKDOWN_TEMPLATE)
    content = template.render(spec=spec, testcases=testcases)
    Path(path).write_text(content, encoding="utf-8")


def render_json_file(path: str | Path, testcases: list[TestCase], spec: TestCaseSpec) -> None:
    """Render generated cases as deterministic JSON for downstream tooling."""
    ensure_parent_dir(path)
    payload = {
        "spec": spec.to_dict(),
        "testcases": [case.to_dict() for case in testcases],
    }
    Path(path).write_text(dump_json(payload) + "\n", encoding="utf-8")
