# templating.py
# Rendering templates (Jinja2) for test output.
from typing import List

from jinja2 import Environment, Template

from .models import TestCase
from .utils import safe_repr

PYTEST_TEMPLATE = """
# Auto-generated pytest file — do not edit by hand unless you intend to import pytest

{% for tc in testcases %}
def test_{{ tc.name | replace(' ', '_') }}():
    {{ tc.description }}
    {% for step in tc.steps %}
    # Step: {{ step.action }}
    # Input: {{ step.input | safe }}
    # Expected: {{ step.expected | safe }}
    # TODO: replace the assertion below with a real call/assertion for your system
    assert True
    {% endfor %}

from .models import TestCase, TestCaseSpec
from .utils import dump_json, ensure_parent_dir, safe_repr, slugify

PYTEST_TEMPLATE = '''"""Auto-generated pytest scenarios for {{ spec.title }}.

Generated by ai-testcase-generator. Review TODO sections and wire them to the
real system under test before treating these tests as production assertions.
"""

import pytest


TEST_CASES = {{ cases_literal }}


@pytest.mark.parametrize("case", TEST_CASES, ids=[case["name"] for case in TEST_CASES])
def test_{{ spec_slug }}(case):
    """{{ spec.description or 'Generated scenario' }}"""
    for step in case["steps"]:
        # Step: {{ "{" }}step['action']{{ "}" }}
        # Input: {{ "{" }}step['input']{{ "}" }}
        # Expected: {{ "{" }}step['expected']{{ "}" }}
        # TODO: call your {{ spec.target }} under test and assert against step["expected"].
        assert step["expected"] is not None
'''

MARKDOWN_TEMPLATE = """# {{ spec.title }} - Generated Test Cases

{{ spec.description }}

**Target:** `{{ spec.target }}`  
**Subject:** `{{ spec.subject }}`

{% for case in testcases %}
## {{ case.id }} - {{ case.name }}

{{ case.description }}

**Tags:** {{ case.tags | join(', ') if case.tags else 'none' }}

{% for step in case.steps %}
### Step {{ loop.index }}

- **Action:** {{ step.action }}
- **Input:** `{{ step.input | safe_repr }}`
- **Expected:** `{{ step.expected | safe_repr }}`
{% endfor %}
{% endfor %}
"""


def serialize_testcases(testcases: List[TestCase]) -> list[dict]:
    """Convert TestCase dataclasses into dictionaries suitable for templates or APIs."""
    serializable_cases = []
    for tc in testcases:
        serializable_cases.append({
            'id': tc.id,
            'name': tc.name,
            'description': tc.description,
            'tags': tc.tags,
            'steps': [
                {
                    'action': s.action,
                    'input': safe_repr(s.input),
                    'expected': safe_repr(s.expected),
                }
                for s in tc.steps
            ],
        })

    return serializable_cases


def render_pytest_content(testcases: List[TestCase], spec=None) -> str:
    """Render pytest source code from a list of TestCase objects."""
    env = Environment()

    # Provide simple filters
    env.filters['safe_repr'] = safe_repr

    template: Template = env.from_string(PYTEST_TEMPLATE)
    return template.render(testcases=serialize_testcases(testcases), spec=spec)


def render_pytest_file(path: str, testcases: List[TestCase], spec=None) -> None:
    """Render a pytest file from a list of TestCase objects and write it to `path`."""
    content = render_pytest_content(testcases, spec=spec)

    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
